name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy code
      uses: easingthemes/ssh-deploy@v3
      with:
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_host: 134.0.10.55
        remote_user: nanocupf9a
        source: https://nanocupf1.com/
